schema_version: "1.0"
mcp_name: "Russian Law MCP"
jurisdiction: "RU"

sources:
  - name: "Official Internet Portal for Legal Information"
    authority: "Administration of the President of the Russian Federation"
    official_portal: "http://pravo.gov.ru/"
    retrieval_method: "HTML_SCRAPE"
    update_frequency: "daily"
    license_or_terms:
      type: "Government Open Data"
      url: "http://pravo.gov.ru/"
      summary: "Russian federal laws not copyrightable per Art. 1259 Civil Code"
    coverage:
      scope: "All federal laws, codes, presidential decrees, government resolutions"
      limitations: "Regional legislation not included. Some historical texts may be OCR-only."
    languages:
      - "ru"

data_freshness:
  automated_checks: true
  check_frequency: "weekly"
  last_verified: "2026-02-25"
